server:
  port: 8010
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: service-consumer-user-ribbon
hystrix:
  metrics:
    polling-interval-ms: 5000