server:
  port: 8080
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenguoku/SpringCloud-config-repository
          username: 
          password:

encrypt:
  key: foo
