server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: service-gateway-zuul
zuul:
  routes:
    abc:  #这个就是个节点  随便起名
      path: /user-url/**
      serviceId: service-provider-user
  prefix: /api    #在访问zuul的地址前面 加上 /api
  strip-prefix: true  # 默认是 true  如果是false 在微服务 的地址前面加 /api
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
